# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('blogId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('blogTitle', models.CharField(max_length=70, verbose_name='Post Title')),
                ('blogSlug', models.SlugField(unique=True)),
                ('blogText', tinymce.models.HTMLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
