# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170719_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='blogId',
            new_name='entryId',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='blogSlug',
            new_name='entrySlug',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='blogText',
            new_name='entryText',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='blogTitle',
            new_name='entryTitle',
        ),
    ]
