# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-09 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreshUserIp',
            fields=[
                ('user_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=150, verbose_name='ip_address')),
                ('location', models.CharField(max_length=150, verbose_name='location')),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
