# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('allergyId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('allergyName', models.CharField(max_length=70, verbose_name='Allergy')),
                ('allergySlug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brandId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('brandName', models.CharField(max_length=70, verbose_name='Brand Name')),
                ('brandSlug', models.SlugField(unique=True)),
                ('brandContactNz', models.CharField(blank=True, max_length=70, verbose_name='Contact NZ')),
                ('brandContactAu', models.CharField(blank=True, max_length=70, verbose_name='Contact Australia')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=70, verbose_name='Category')),
                ('categorySlug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=150, verbose_name='Brand Name')),
                ('productFlavour', models.CharField(max_length=150, verbose_name='Product Flavour')),
                ('productImage', models.ImageField(blank=True, upload_to='media/products', verbose_name='Product Image')),
                ('productAllergies', models.ManyToManyField(blank=True, to='products.Allergy', verbose_name='Allergies')),
                ('productBrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Brand', verbose_name='Brand')),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='Category')),
            ],
        ),
    ]
