# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'ordering': ['allergyName']},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brandName']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['categoryName']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['productBrand', 'productName', 'productFlavour']},
        ),
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(max_length=150, verbose_name='Product Name'),
        ),
    ]
