# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170715_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productFlavour',
            field=models.CharField(blank=True, max_length=150, verbose_name='Product Flavour'),
        ),
    ]
