# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170721_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(blank=True, upload_to='media/products', verbose_name='Product Image'),
        ),
    ]
