# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-23 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170721_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('featured_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=70, verbose_name='product_id')),
                ('username', models.CharField(blank=True, max_length=70, verbose_name='username')),
                ('featured_product', models.CharField(blank=True, max_length=70, verbose_name='featured_product')),
            ],
            options={
                'ordering': ['featured_id'],
            },
        ),
    ]
