# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-08 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_featured_featured_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=150, verbose_name='user email')),
                ('code', models.CharField(max_length=150, verbose_name='code')),
                ('used', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
